# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-CLI
version:      1.09
version_from: lib/LEOCHARRE/CLI.pm
installdirs:  site
requires:
    Carp:                          0
    File::chmod:                   0
    File::Which:                   0
    Getopt::Std:                   0
    LEOCHARRE::DEBUG:              0
    Linux::usermod:                0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
